{
    "name": "GSLab Backend Theme",
    "summary": "YABT based on responsive web client and inspired by Openworx",
    "version": "15.0.1.1.0",
    "category": "Themes/Backend",
    "website": "https://www.gslab.it",
    "author": "Giovanni - GSLab",
    "live_test_url": "https://odoo.gslab.it",
    "price": "49",
    "currency": "EUR",
    "license": "LGPL-3",
    "support": "giovanni@gslab.it",
    "installable": True,
    "depends": ['base_setup', 'mail'],
    "data": [
        "views/res_users.xml",
        "views/web.xml",
        "views/res_config_settings_views.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "/gslab_backend_theme/static/src/legacy/js/website_apps_menu.js",
            "/gslab_backend_theme/static/src/legacy/scss/website_apps_menu.scss",
        ],
        "web.assets_backend": [
            "/gslab_backend_theme/static/src/css/colors.gen.scss",
            "/gslab_backend_theme/static/src/css/variables.scss",
            "/gslab_backend_theme/static/src/legacy/scss/web_responsive.scss",
            "/gslab_backend_theme/static/src/legacy/js/web_responsive.js",
            "/gslab_backend_theme/static/src/legacy/scss/kanban_view_mobile.scss",
            "/gslab_backend_theme/static/src/legacy/js/kanban_renderer_mobile.js",
            "/gslab_backend_theme/static/src/components/ui_context.esm.js",
            "/gslab_backend_theme/static/src/components/apps_menu/apps_menu.scss",
            "/gslab_backend_theme/static/src/components/apps_menu/apps_menu.esm.js",
            "/gslab_backend_theme/static/src/components/navbar/main_navbar.scss",
            "/gslab_backend_theme/static/src/components/control_panel/control_panel.scss",
            "/gslab_backend_theme/static/src/components/control_panel/control_panel.esm.js",
            "/gslab_backend_theme/static/src/components/search_panel/search_panel.scss",
            "/gslab_backend_theme/static/src/components/search_panel/search_panel.esm.js",
            "/gslab_backend_theme/static/src/components/attachment_viewer/attachment_viewer.scss",
            "/gslab_backend_theme/static/src/components/attachment_viewer/attachment_viewer.esm.js",
            "/gslab_backend_theme/static/src/components/hotkey/hotkey.scss",

            "/gslab_backend_theme/static/src/css/web.scss",
            "/gslab_backend_theme/static/src/css/button.scss",
            "/gslab_backend_theme/static/src/css/calendar.scss",
            "/gslab_backend_theme/static/src/css/form.scss",
            "/gslab_backend_theme/static/src/css/list.scss",
            "/gslab_backend_theme/static/src/css/nav_tab.scss",
            "/gslab_backend_theme/static/src/css/search_view_mobile.scss",
            "/gslab_backend_theme/static/src/css/search.scss",
            "/gslab_backend_theme/static/src/css/tooltip.scss",
        ],
        "web.assets_qweb": [
            "/gslab_backend_theme/static/src/xml/form_buttons.xml",
            "/gslab_backend_theme/static/src/components/apps_menu/apps_menu.xml",
            "/gslab_backend_theme/static/src/components/control_panel/control_panel.xml",
            "/gslab_backend_theme/static/src/components/navbar/main_navbar.xml",
            "/gslab_backend_theme/static/src/components/search_panel/search_panel.xml",
            "/gslab_backend_theme/static/src/components/attachment_viewer/attachment_viewer.xml",
            "/gslab_backend_theme/static/src/components/hotkey/hotkey.xml",
            "/gslab_backend_theme/static/src/xml/custom/apps_menu.xml",

        ],
    },
    "images": [
        'static/description/banner.png',
        'static/description/theme_screenshot.png',
    ],
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook'
}
